# -*- coding: utf-8 -*-
"""studentsuccessanalyzer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nyeGP6mWnhNbg_y4adwXRchxSUtX_jVw
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine

# Set visual style
sns.set_theme(style="whitegrid")
# %matplotlib inline

# Load the dataset
df = pd.read_csv('/content/ultimate_student_productivity_dataset_5000.csv')
print(df.info())
display(df.head())
display(df.describe())

# Create an in-memory SQL database from the dataframe
engine = create_engine('sqlite://')
df.to_sql('students', engine, index=False)

# Query: High Social Media usage vs Average Productivity
query = """
SELECT Academic_Level, AVG(Productivity_Score) as Avg_Prod
FROM students
WHERE Social_Media_hours > 4
GROUP BY Academic_Level
ORDER BY Avg_Prod DESC
"""
pd.read_sql(query, engine)

plt.figure(figsize=(12, 8))
correlation_matrix = df.corr(numeric_only=True)
sns.heatmap(correlation_matrix, annot=True, cmap='RdBu', fmt=".2f")
plt.title("Correlation: Habits vs. Academic Performance")
plt.show()

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='study_hours', y='burnout_level', hue='mental_health_score', palette='viridis')
plt.title("Study Hours vs. Burnout (Colored by Mental Health)")
plt.show()

# Creating a composite feature
df['Digital_Distraction_Score'] = df['social_media_hours'] + df['gaming_hours']

# Checking how it impacts the Focus Index
sns.lmplot(x='Digital_Distraction_Score', y='focus_index', data=df, line_kws={'color': 'red'})
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score
from sklearn.preprocessing import LabelEncoder

# 1. Encode categorical variables (Gender, Academic Level, etc.)
le = LabelEncoder()
df_ml = df.copy()

categorical_cols = df_ml.select_dtypes(include=['object']).columns
for col in categorical_cols:
    df_ml[col] = le.fit_transform(df_ml[col])

# 2. Define Features (X) and Target (y)
# We exclude all targets to predict just the Exam Score for now
targets = ['focus_index', 'burnout_level', 'productivity_score', 'exam_score']
X = df_ml.drop(columns=targets)
y = df_ml['exam_score']

# 3. Split into Training (80%) and Testing (20%) sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Initialize and Train
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

# Make Predictions
y_pred = model.predict(X_test)

# Evaluate
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error: {mae:.2f} points")
print(f"R-Squared Score: {r2:.2f}")

# Get importance levels
importances = model.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({'Feature': feature_names, 'Importance': importances}).sort_values(by='Importance', ascending=False)

# Plot
plt.figure(figsize=(10, 6))
sns.barplot(x='Importance', y='Feature', data=feature_importance_df, palette='magma')
plt.title('Which Factors Predict Exam Scores the Best?')
plt.show()

plt.figure(figsize=(8, 8))
plt.scatter(y_test, y_pred, alpha=0.5, color='teal')
plt.plot([y_test.min(), y_test.max()], [y_test.min(), y_test.max()], 'r--', lw=2)
plt.xlabel('Actual Exam Score')
plt.ylabel('Predicted Exam Score')
plt.title('Model Accuracy: Actual vs. Predicted')
plt.show()

from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, ConfusionMatrixDisplay

# Define a threshold for "High Risk"
threshold = df['burnout_level'].quantile(0.75)
df_ml['burnout_risk'] = (df_ml['burnout_level'] > threshold).astype(int)

# Define features (X) and the new classification target (y)
# We drop all potential leakage variables (other target variables)
X_class = df_ml.drop(columns=['focus_index', 'burnout_level', 'productivity_score', 'exam_score', 'burnout_risk'])
y_class = df_ml['burnout_risk']

# Split the data
X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(X_class, y_class, test_size=0.2, random_state=42)

# Initialize and Train
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train_c, y_train_c)

# Predict
y_pred_c = clf.predict(X_test_c)

# Print Performance Report
print(classification_report(y_test_c, y_pred_c, target_names=['Low/Med Risk', 'High Risk']))

# Plot the Confusion Matrix
fig, ax = plt.subplots(figsize=(8, 6))
ConfusionMatrixDisplay.from_estimator(clf, X_test_c, y_test_c,
                                      display_labels=['Stable', 'High Risk'],
                                      cmap='Reds', ax=ax)
plt.title('Burnout Risk Detection Accuracy')
plt.grid(False) # Clean up the visual
plt.show()

# Grouping data by Study Hours to see the average trend
trend_df = df.groupby('study_hours')[['exam_score', 'burnout_level']].mean().reset_index()

fig, ax1 = plt.subplots(figsize=(12, 6))

# Plot Exam Score
color = 'tab:blue'
ax1.set_xlabel('Study Hours (Daily)')
ax1.set_ylabel('Average Exam Score', color=color)
sns.lineplot(data=trend_df, x='study_hours', y='exam_score', ax=ax1, color=color, marker='o', label='Exam Score')
ax1.tick_params(axis='y', labelcolor=color)

# Create a second y-axis for Burnout
ax2 = ax1.twinx()
color = 'tab:red'
ax2.set_ylabel('Average Burnout Level', color=color)
sns.lineplot(data=trend_df, x='study_hours', y='burnout_level', ax=ax2, color=color, marker='x', label='Burnout Level')
ax2.tick_params(axis='y', labelcolor=color)

plt.title('The Academic Sweet Spot: Finding the Balance')
fig.tight_layout()
plt.show()

# Calculate Efficiency Ratio
trend_df['Efficiency_Ratio'] = trend_df['exam_score'] / trend_df['burnout_level']

plt.figure(figsize=(10, 5))
sns.lineplot(data=trend_df, x='study_hours', y='Efficiency_Ratio', color='green', lw=3)
plt.axvline(x=trend_df.loc[trend_df['Efficiency_Ratio'].idxmax(), 'study_hours'], color='orange', linestyle='--', label='Peak Efficiency')

plt.title('Student Efficiency: When is Study Time Most "Profitable"?')
plt.ylabel('Score-to-Burnout Ratio')
plt.legend()
plt.show()

best_hour = trend_df.loc[trend_df['Efficiency_Ratio'].idxmax(), 'study_hours']
print(f"The statistical 'Sweet Spot' for this dataset is {best_hour} study hours per day.")

plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='sleep_hours', y='focus_index', hue='caffeine_intake_mg', size='caffeine_intake_mg', palette='copper', alpha=0.6)
plt.title('The Sleep-Caffeine-Focus Triangle')
plt.show()

def student_advisor(student_data):
    """
    Inputs: A dictionary or Series containing student habits.
    Outputs: Predicted Score, Burnout Risk, and a tailored Advice string.
    """
    # 1. Prepare data for the models (dropping target columns)
    features = student_data.drop(['focus_index', 'burnout_level', 'productivity_score', 'exam_score'], errors='ignore')
    features_reshaped = features.values.reshape(1, -1)

    # 2. Get Predictions
    predicted_score = model.predict(X_test.iloc[0:1])[0] # Using model from previous step
    burnout_risk = clf.predict(X_test_c.iloc[0:1])[0]     # Using classifier from previous step

    # 3. Logic-based Advice
    advice = []
    if burnout_risk == 1:
        advice.append("⚠️ HIGH BURNOUT RISK: Prioritize increasing Sleep Hours and reducing Screen Time.")
    if student_data['study_hours'] > 8:
        advice.append("💡 DIMINISHING RETURNS: Your study hours are high; focus on 'Deep Work' rather than more hours.")
    if student_data['sleep_hours'] < 6:
        advice.append("😴 SLEEP DEPRAVITY: Increasing sleep to 7+ hours could boost your Focus Index by ~15%.")
    if not advice:
        advice.append("✅ STEADY PROGRESS: Your habits are well-balanced. Keep it up!")

    return {
        "Predicted Exam Score": round(predicted_score, 2),
        "Risk Status": "High" if burnout_risk == 1 else "Stable",
        "Recommendations": advice
    }

# Test it on a random student from the test set
sample_student = X_test.iloc[10]
report = student_advisor(sample_student)

print(f"--- STUDENT REPORT CARD ---")
print(f"Predicted Score: {report['Predicted Exam Score']}")
print(f"Burnout Risk: {report['Risk Status']}")
print("\nAdvisor Recommendations:")
for line in report['Recommendations']:
    print(f"- {line}")

# Comparing one student to the average
student_id = 42 # Student ID
student_stats = df.iloc[student_id][['study_hours', 'sleep_hours', 'social_media_hours', 'caffeine_intake_mg']]
average_stats = df[['study_hours', 'sleep_hours', 'social_media_hours', 'caffeine_intake_mg']].mean()

comparison_df = pd.DataFrame({'You': student_stats, 'Average': average_stats})
comparison_df.plot(kind='bar', figsize=(10, 5), color=['teal', 'gray'])
plt.title(f"Student #{student_id} vs. Class Average")
plt.ylabel('Hours / Units')
plt.show()

# Create bins for clearer visualization
df['Sleep_Bin'] = pd.cut(df['sleep_hours'], bins=[0, 5, 7, 9, 12], labels=['Poor', 'Fair', 'Good', 'Excellent'])
df['Study_Bin'] = pd.cut(df['study_hours'], bins=[0, 3, 6, 9, 15], labels=['Low', 'Moderate', 'High', 'Extreme'])

pivot_table = df.pivot_table(values='exam_score', index='Sleep_Bin', columns='Study_Bin', aggfunc='mean')

plt.figure(figsize=(10, 6))
sns.heatmap(pivot_table, annot=True, cmap="YlGnBu", fmt=".1f")
plt.title("The Success Matrix: Sleep vs. Study Impact on Scores")
plt.show()

import ipywidgets as widgets
from IPython.display import display, clear_output
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. PRE-CALCULATE DATASET AVERAGES
avg_stats = df.mean(numeric_only=True)

# 2. CREATE UI COMPONENTS
style = {'description_width': 'initial'}
layout = widgets.Layout(width='320px')

# Habit Sliders
age_in = widgets.IntSlider(value=18, min=15, max=25, description='Age', style=style, layout=layout)
study_in = widgets.IntSlider(value=6, min=0, max=15, description='Study Hours', style=style, layout=layout)
sleep_in = widgets.IntSlider(value=7, min=0, max=12, description='Sleep Hours', style=style, layout=layout)
screen_in = widgets.IntSlider(value=5, min=0, max=18, description='Screen Time', style=style, layout=layout)
caffeine_in = widgets.IntSlider(value=100, min=0, max=500, step=50, description='Caffeine (mg)', style=style, layout=layout)
exercise_in = widgets.IntSlider(value=30, min=0, max=120, description='Exercise (min)', style=style, layout=layout)

# Goal Setting
target_score_in = widgets.IntSlider(value=85, min=50, max=100, description='Target Score %',
                                   style={'description_width': 'initial', 'handle_color': '#f39c12'}, layout=layout)

predict_btn = widgets.Button(description='Analyze All Factors', button_style='primary', icon='dna', layout=widgets.Layout(width='250px'))
output_area = widgets.Output()

# 3. PREDICTION & BURNOUT PREVENTION LOGIC
def on_analyze_clicked(b):
    with output_area:
        clear_output(wait=True)

        # A. Setup current input based on X_test template
        input_row = X_test.iloc[0:1].copy()
        user_inputs = {
            'age': age_in.value,
            'study_hours': study_in.value,
            'sleep_hours': sleep_in.value,
            'screen_time_hours': screen_in.value,
            'caffeine_intake_mg': caffeine_in.value,
            'exercise_minutes': exercise_in.value
        }
        for col, val in user_inputs.items():
            input_row[col] = val

        input_df = input_row[X_train.columns]

        # Predictions
        pred_score = model.predict(input_df)[0]
        burnout_risk = clf.predict(input_df)[0]

        # B. Ideal Success Profile Logic (Filtering for Target Score)
        target = target_score_in.value
        ideal_group = df[(df['exam_score'] >= target - 2) & (df['exam_score'] <= target + 2)]
        if ideal_group.empty:
            ideal_group = df.nlargest(int(len(df)*0.05), 'exam_score')

        ideal_habits = ideal_group.mean(numeric_only=True)

        # C. DISPLAY RESULTS
        print(f"--- 🛡️ FULL-FACTOR AI REPORT ---")
        print(f"PREDICTED SCORE: {round(pred_score, 1)}% | TARGET: {target}%")

        if burnout_risk == 1:
            print("🚨 ALERT: High Burnout Risk! High caffeine and low sleep are a dangerous combo.")
        else:
            print("✅ WELLBEING: Your lifestyle balance supports long-term success.")
        print("-" * 60)

        # D. VISUAL COMPARISON (Two Subplots for different scales)

        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 6))

        # Chart 1: Time-based (Hours)
        labels_h = ['Study', 'Sleep', 'Screen']
        user_h = [study_in.value, sleep_in.value, screen_in.value]
        ideal_h = [ideal_habits['study_hours'], ideal_habits['sleep_hours'], ideal_habits['screen_time_hours']]

        x = np.arange(len(labels_h))
        ax1.bar(x - 0.2, user_h, 0.4, label='You', color='#3498db')
        ax1.bar(x + 0.2, ideal_h, 0.4, label=f'Ideal for {target}%', color='#2ecc71', alpha=0.6)
        ax1.set_xticks(x)
        ax1.set_xticklabels(labels_h)
        ax1.set_ylabel('Hours')
        ax1.set_title('Time Management')
        ax1.legend()

        # Chart 2: Intensity-based (Age, Caffeine, Exercise)
        labels_i = ['Age', 'Caffeine', 'Exercise']
        user_i = [age_in.value, caffeine_in.value, exercise_in.value]
        ideal_i = [ideal_habits['age'], ideal_habits['caffeine_intake_mg'], ideal_habits['exercise_minutes']]

        x2 = np.arange(len(labels_i))
        ax2.bar(x2 - 0.2, user_i, 0.4, label='You', color='#9b59b6')
        ax2.bar(x2 + 0.2, ideal_i, 0.4, label=f'Ideal for {target}%', color='#f1c40f', alpha=0.6)
        ax2.set_xticks(x2)
        ax2.set_xticklabels(labels_i)
        ax2.set_ylabel('Units (Years/mg/min)')
        ax2.set_title('Lifestyle Factors')
        ax2.legend()

        plt.tight_layout()
        plt.show()

# 4. ORGANIZE AND DISPLAY
predict_btn.on_click(on_analyze_clicked)

dashboard_ui = widgets.VBox([
    widgets.HTML("<h2>🎓 Full-Factor AI Success Planner</h2>"),
    widgets.HBox([
        widgets.VBox([widgets.HTML("<b>⚙️ Lifestyle Settings</b>"), age_in, study_in, sleep_in, screen_in, caffeine_in, exercise_in]),
        widgets.VBox([widgets.HTML("<b>🎯 Target Goal</b>"), target_score_in])
    ]),
    widgets.Box([predict_btn], layout=widgets.Layout(padding='20px 0px')),
    output_area
])

display(dashboard_ui)